// This file was generated by Rcpp::compileAttributes
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <RcppArmadillo.h>
#include <Rcpp.h>

using namespace Rcpp;

// util_module
List util_module(NumericMatrix cashR, NumericMatrix saveR, NumericMatrix EVR, NumericVector hsizeR, NumericVector laborR, List par, bool b, bool quad);
RcppExport SEXP umod_util_module(SEXP cashRSEXP, SEXP saveRSEXP, SEXP EVRSEXP, SEXP hsizeRSEXP, SEXP laborRSEXP, SEXP parSEXP, SEXP bSEXP, SEXP quadSEXP) {
BEGIN_RCPP
    Rcpp::RNGScope __rngScope;
    NumericMatrix cashR = Rcpp::as<NumericMatrix >(cashRSEXP);
    NumericMatrix saveR = Rcpp::as<NumericMatrix >(saveRSEXP);
    NumericMatrix EVR = Rcpp::as<NumericMatrix >(EVRSEXP);
    NumericVector hsizeR = Rcpp::as<NumericVector >(hsizeRSEXP);
    NumericVector laborR = Rcpp::as<NumericVector >(laborRSEXP);
    List par = Rcpp::as<List >(parSEXP);
    bool b = Rcpp::as<bool >(bSEXP);
    bool quad = Rcpp::as<bool >(quadSEXP);
    List __result = util_module(cashR, saveR, EVR, hsizeR, laborR, par, b, quad);
    return Rcpp::wrap(__result);
END_RCPP
}
// util_module_file
List util_module_file(NumericMatrix cashR, NumericMatrix EVR, NumericVector hsizeR, NumericVector laborR, List par, bool quad);
RcppExport SEXP umod_util_module_file(SEXP cashRSEXP, SEXP EVRSEXP, SEXP hsizeRSEXP, SEXP laborRSEXP, SEXP parSEXP, SEXP quadSEXP) {
BEGIN_RCPP
    Rcpp::RNGScope __rngScope;
    NumericMatrix cashR = Rcpp::as<NumericMatrix >(cashRSEXP);
    NumericMatrix EVR = Rcpp::as<NumericMatrix >(EVRSEXP);
    NumericVector hsizeR = Rcpp::as<NumericVector >(hsizeRSEXP);
    NumericVector laborR = Rcpp::as<NumericVector >(laborRSEXP);
    List par = Rcpp::as<List >(parSEXP);
    bool quad = Rcpp::as<bool >(quadSEXP);
    List __result = util_module_file(cashR, EVR, hsizeR, laborR, par, quad);
    return Rcpp::wrap(__result);
END_RCPP
}
// ufun_Attanasio
NumericMatrix ufun_Attanasio(NumericMatrix ResR, NumericVector sR, List par);
RcppExport SEXP umod_ufun_Attanasio(SEXP ResRSEXP, SEXP sRSEXP, SEXP parSEXP) {
BEGIN_RCPP
    Rcpp::RNGScope __rngScope;
    NumericMatrix ResR = Rcpp::as<NumericMatrix >(ResRSEXP);
    NumericVector sR = Rcpp::as<NumericVector >(sRSEXP);
    List par = Rcpp::as<List >(parSEXP);
    NumericMatrix __result = ufun_Attanasio(ResR, sR, par);
    return Rcpp::wrap(__result);
END_RCPP
}
